url: https://caillougbh.github.io
baseurl: ""

# Caillou Bao G. Hoang
caillou.gbh@gmail.com

## About Me
I am a student at Richland High School and I have always had a love for gaming and coding, which drove my interest in Computer Science.

## Skills
- Languages:
  + Java
  + JavaScript
  + Python
- Problem-Solving and Math

## Career Goals
I want to thrive in a tech-based career, possibly engineering.
