url: https://caillougbh.github.io
baseurl: ""

# Site settings
title: "About Me - Caillou B. G. Hoang"
email: "caillou.gbh@gmail.com"
description: "I am a student at Richland High School and I have always had a love for gaming and coding, which drove my interest in Computer Science."

# Team names, titles and social links
people:
- name: 
  pic: 
  position: 
  social:
    - title: #
      url: #
    - title: #
      url: #
    - title: #
      url: #

- name: I HOPE THIS WORKS
  pic: 
  position: ME
  social:
    - title: e
      url: #
    - title: f
      url: #
    - title: g
      url: #

- name: 
  pic: 
  position: 
  social:
    - title: #
      url: #
    - title: #
      url: #
    - title: #
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 930 Long Ave, WA

# Build settings
markdown: kramdown
permalink: pretty
permalink: pretty
